name: Deploy on Code Changes

on:
  push:
    branches:
      - main # Trigger on the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for code changes
        id: file_check
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          if ! grep -E '\.(js|jsx|ts|tsx|css|scss|html|json)' changed_files.txt; then
            echo "No code changes detected. Skipping deployment."
            exit 0
          fi

      - name: Deploy to Vercel
        if: success()
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Add your Vercel token in GitHub secrets
          vercel-args: "--prod"
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Add your project ID in GitHub secrets
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Add your org ID in GitHub secrets
